version: "3.7"

services:
  db:
    image: postgres:11-alpine
    env_file:
      - build/docker.env
    ports:
      - "6432:5432"

  backend:
    depends_on:
      - db
      - d-transformer
    build:
      context: ./
      dockerfile: build/Dockerfile-dev

    entrypoint: sh -c './build/wait-for db:5432 -- go run -mod=vendor main.go'

    ports:
      - "8080:8080"
    env_file:
      - build/docker.env
    environment:
      - JOBS_DB_HOST=db
  d-transformer:
    build:
      context: ./rudder-transformer/
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  replay-db:
    image: postgres:11-alpine
    env_file:
      - ../replay-server/rudder-server/build/docker.env
    ports:
      - "6433:5432"

  replay-backend:
    depends_on:
      - replay-db
      - replay-d-transformer
    build:
      context: ../replay-server/rudder-server
      dockerfile: build/Dockerfile-dev

    entrypoint: sh -c './build/wait-for replay-db:5432 -- go run -mod=vendor main.go'

    ports:
      - "8081:8080"
    env_file:
      - ../replay-server/rudder-server/build/docker.env
    environment:
      - JOBS_DB_HOST=replay-db
  replay-d-transformer:
    build:
      context: ../replay-server/rudder-server/rudder-transformer
      dockerfile: Dockerfile
    ports:
      - "9091:9090"

  enterprise-db:
    image: postgres:11-alpine
    env_file:
      - ../rudder-enterprise/build/docker.env
    ports:
      - "6434:5432"

  enterprise-backend:
    depends_on:
      - enterprise-db
      - replay-backend
    build:
      context: ../rudder-enterprise
      dockerfile: build/Dockerfile

    entrypoint: sh -c './build/wait-for enterprise-db:5432 -- go run -mod=vendor main.go'

    ports:
      - "8082:8080"
    env_file:
      - ../rudder-enterprise/build/docker.env
    environment:
      - JOBS_DB_HOST=enterprise-db
